<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classroom extends \App\Entity\Classroom implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'teachers', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'students', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'controles'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'teachers', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'students', '' . "\0" . 'App\\Entity\\Classroom' . "\0" . 'controles'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Classroom $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Classroom
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): \App\Entity\Classroom
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getTeachers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTeachers', []);

        return parent::getTeachers();
    }

    /**
     * {@inheritDoc}
     */
    public function addTeacher(\App\Entity\Teacher $teacher): \App\Entity\Classroom
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTeacher', [$teacher]);

        return parent::addTeacher($teacher);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTeacher(\App\Entity\Teacher $teacher): \App\Entity\Classroom
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTeacher', [$teacher]);

        return parent::removeTeacher($teacher);
    }

    /**
     * {@inheritDoc}
     */
    public function getStudents(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStudents', []);

        return parent::getStudents();
    }

    /**
     * {@inheritDoc}
     */
    public function addStudent(\App\Entity\Student $student): \App\Entity\Classroom
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStudent', [$student]);

        return parent::addStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStudent(\App\Entity\Student $student): \App\Entity\Classroom
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStudent', [$student]);

        return parent::removeStudent($student);
    }

    /**
     * {@inheritDoc}
     */
    public function getControles(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getControles', []);

        return parent::getControles();
    }

    /**
     * {@inheritDoc}
     */
    public function addControle(\App\Entity\Controle $controle): \App\Entity\Classroom
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addControle', [$controle]);

        return parent::addControle($controle);
    }

    /**
     * {@inheritDoc}
     */
    public function removeControle(\App\Entity\Controle $controle): \App\Entity\Classroom
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeControle', [$controle]);

        return parent::removeControle($controle);
    }

}
