<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qzh.j69' shared service.

return $this->privates['.service_locator.qzh.j69'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('passwordEncoder' => function () {
    return ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php'));
}, 'user' => function (): \App\Entity\User {
    return ($this->privates['.errored..service_locator.qzh.j69.App\Entity\User'] ?? $this->load('getUserService.php'));
}));
