<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.qkaFMmv' shared service.

return $this->privates['.service_locator.qkaFMmv'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('user' => function (): \Symfony\Component\Security\Core\User\UserInterface {
    return ($this->privates['.errored..service_locator.qkaFMmv.Symfony\Component\Security\Core\User\UserInterface'] ?? $this->load('getUserInterfaceService.php'));
}));
