<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Omines\DataTablesBundle\Adapter\ArrayAdapter' autowired service.

include_once $this->targetDirs[3].'/vendor/omines/datatables-bundle/src/Adapter/AdapterInterface.php';
include_once $this->targetDirs[3].'/vendor/omines/datatables-bundle/src/Adapter/ArrayAdapter.php';

$this->factories['service_container']['Omines\DataTablesBundle\Adapter\ArrayAdapter'] = function () {
    return new \Omines\DataTablesBundle\Adapter\ArrayAdapter();
};

return $this->factories['service_container']['Omines\DataTablesBundle\Adapter\ArrayAdapter']();
