<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Omines\DataTablesBundle\Column\TwigColumn' autowired service.

include_once $this->targetDirs[3].'/vendor/omines/datatables-bundle/src/Column/AbstractColumn.php';
include_once $this->targetDirs[3].'/vendor/omines/datatables-bundle/src/Column/TwigColumn.php';

$this->factories['service_container']['Omines\DataTablesBundle\Column\TwigColumn'] = function () {
    return new \Omines\DataTablesBundle\Column\TwigColumn(($this->services['twig'] ?? $this->getTwigService()));
};

return $this->factories['service_container']['Omines\DataTablesBundle\Column\TwigColumn']();
