<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\MyStudentsController::MyStudentsManager' => function () {
    return ($this->privates['.service_locator.qkaFMmv'] ?? $this->load('get_ServiceLocator_QkaFMmvService.php'));
}, 'App\\Controller\\ResettingController::request' => function () {
    return ($this->privates['.service_locator.eoSwcpv'] ?? $this->load('get_ServiceLocator_EoSwcpvService.php'));
}, 'App\\Controller\\ResettingController::resetting' => function () {
    return ($this->privates['.service_locator.qzh.j69'] ?? $this->load('get_ServiceLocator_Qzh_J69Service.php'));
}, 'App\\Controller\\UserController::registerForm' => function () {
    return ($this->privates['.service_locator.cPEJcDm'] ?? $this->load('get_ServiceLocator_CPEJcDmService.php'));
}, 'App\\Controller\\MyStudentsController:MyStudentsManager' => function () {
    return ($this->privates['.service_locator.qkaFMmv'] ?? $this->load('get_ServiceLocator_QkaFMmvService.php'));
}, 'App\\Controller\\ResettingController:request' => function () {
    return ($this->privates['.service_locator.eoSwcpv'] ?? $this->load('get_ServiceLocator_EoSwcpvService.php'));
}, 'App\\Controller\\ResettingController:resetting' => function () {
    return ($this->privates['.service_locator.qzh.j69'] ?? $this->load('get_ServiceLocator_Qzh_J69Service.php'));
}, 'App\\Controller\\UserController:registerForm' => function () {
    return ($this->privates['.service_locator.cPEJcDm'] ?? $this->load('get_ServiceLocator_CPEJcDmService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
