<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSO244Ny\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSO244Ny/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSO244Ny.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSO244Ny\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSO244Ny\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'SO244Ny',
    'container.build_id' => 'ab6d1ade',
    'container.build_time' => 1539344399,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSO244Ny');
