<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNWF1eds\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNWF1eds/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNWF1eds.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNWF1eds\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNWF1eds\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'NWF1eds',
    'container.build_id' => '54fb436d',
    'container.build_time' => 1539243775,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerNWF1eds');
